#!/bin/bash
DISCORD_URL="https://discordapp.com/api/download/stable?platform=linux&format=deb"
VENCORD_URL="https://github.com/Vencord/Installer/releases/latest/download/VencordInstallerCli-linux"
set -e
pushd /tmp/ >/dev/null

if [[ $UID == 0 ]]; then
printf "This script will run correctly as a normal user. Please \e[1;31mdo not\e[0m run this script as root!\n"
exit
fi

printf "Getting newest discord DEB package...\n"
sudo su << EOF
wget -O /tmp/discord-installer.deb "$DISCORD_URL"
printf "Installing discord DEB package...\n"
dpkg -i discord-installer.deb
printf "Downloading...\n"
curl "$VENCORD_URL" -Lo vencord-installer >/dev/null
chmod +x vencord-installer
printf "Installing...\n"
/tmp/vencord-installer --branch stable --install >/dev/null
rm /tmp/vencord-installer -f
rm /tmp/discord-installer.deb -f
EOF

